# This is a config for E2B sandbox template.
# You can use template ID (f5jrp57kiap33rqbo50v) or template name (vibe-nextjs-prod) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-prod") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-prod") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-prod')

team_id = "61278959-c6d4-44c2-9443-841d1cc4c103"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-prod"
template_id = "f5jrp57kiap33rqbo50v"
